if __name__ == '__main__':
    print('Task 13. Coordinate.')
x = input("Type a value for x: ")
x = int(x)
y = input("Type a value for y: ")
y = int(y)
z = input("Type a value for z: ")
z = int(z)
coordinate = (x, y, z)
print('Coordinate ' + str(coordinate))